"""Update Category model

Revision ID: ec397cca0e97
Revises: fdcb184fa860
Create Date: 2025-10-04 05:07:13.443602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec397cca0e97'
down_revision: Union[str, None] = 'fdcb184fa860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('point_type', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'categories', ['point_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'point_type')
    # ### end Alembic commands ###
