"""Update point model

Revision ID: 159435284097
Revises: ec397cca0e97
Create Date: 2025-10-04 05:54:30.974034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '159435284097'
down_revision: Union[str, None] = 'ec397cca0e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('points', 'route_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('points', 'route_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
